name: quran
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  api_service:
    path: ./packages/api_service
  auto_route: ^5.0.2
  dartz: ^0.10.1
  database_service:
    path: ./packages/database_service
  dio: ^4.0.6
  dropdown_search: ^5.0.3
  flutter_bloc: ^8.1.1
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.11
  flutter_screenutil: ^5.5.4
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^1.5.3
  json_annotation: ^4.7.0
  logger: ^1.1.0
  lottie: ^1.4.3
  ndialog: ^4.2.0
  pin_code_fields: ^7.4.0
  pull_to_refresh: ^2.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  hive_generator: ^1.1.3
  injectable_generator: ^1.5.4
  json_serializable: ^6.5.1

flutter:
  uses-material-design: true
