name: quran
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.2+3

environment:
  sdk: ^3.5.2
dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter  
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  hooks_riverpod: ^2.5.2
  json_annotation: ^4.9.0
  just_audio: ^0.9.40
  lottie: ^3.1.2
  path_provider: ^2.1.4
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.7.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lint: ^2.3.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
dependency_overrides:
  just_audio_web: ^0.4.12

flutter_gen:
  output: lib/src/config/gen/
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/pngs/
    - assets/animations/
    - assets/svgs/

  fonts:
    - family: Morabbae
      fonts:
        - asset: assets/fonts/Morabba-Black.ttf
          weight: 900
        - asset: assets/fonts/Morabba-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Morabba-Bold.ttf
          weight: 700
        - asset: assets/fonts/Morabba-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Morabba-Medium.ttf
          weight: 500
        - asset: assets/fonts/Morabba-Regular.ttf
          weight: 400
        - asset: assets/fonts/Morabba-Light.ttf
          weight: 200
        - asset: assets/fonts/Morabba-UltraLight.ttf
          weight: 100
    - family: AlQalamNew
      fonts:
        - asset: assets/fonts/al_qalam_new/al_qalam_new.ttf
