name: api_service
description: API Service Package.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0

flutter: null
